
WALL  =  "⛓"
PLAYER = "🤖"
GANADOR ="🐱‍🚀"
BOX =    "📀"
CAJ =    "💿"
GOALS =  "🏁"
SPACE =  "🎫"


tablero = (
    [WALL, WALL, WALL, WALL, WALL, WALL, WALL,WALL],
    [WALL, SPACE, SPACE, SPACE, SPACE, GOALS, WALL],
    [WALL, SPACE, SPACE, SPACE, SPACE, SPACE, WALL],
    [WALL, SPACE, SPACE, SPACE, SPACE, SPACE, WALL],
    [WALL, SPACE, SPACE, SPACE, SPACE, SPACE, WALL],
    [WALL, SPACE, SPACE, SPACE, SPACE, SPACE, WALL],
    [WALL, PLAYER, CAJ, SPACE,  SPACE, SPACE, WALL],
    [WALL, SPACE, SPACE, SPACE, SPACE, SPACE, WALL],
    [WALL, SPACE, SPACE, SPACE, SPACE, SPACE, WALL],
    [WALL, WALL, WALL, WALL, WALL, WALL, WALL,WALL],
)
 