
WALL  =  "⛓"
PLAYER = "🤖"
GANADOR ="🐱‍🚀"
BOX =    "🎁"
GOALS =  "🏁"
SPACE =  "🎫"


tablero = (
    [WALL,  WALL,  WALL,  WALL, WALL,  WALL,  WALL],
    [WALL, SPACE, SPACE, SPACE, SPACE, GOALS, WALL],
    [WALL, SPACE, SPACE, SPACE, SPACE, SPACE, WALL],
    [WALL, SPACE, SPACE, SPACE, SPACE, SPACE, WALL],
    [WALL, SPACE, SPACE, SPACE, SPACE, SPACE, WALL],
    [WALL, SPACE, SPACE, SPACE, SPACE, SPACE, WALL],
    [WALL, PLAYER, BOX, SPACE,  SPACE, SPACE, WALL],
    [WALL, SPACE, SPACE, SPACE, SPACE, SPACE, WALL],
    [WALL, SPACE, SPACE, SPACE, SPACE, SPACE, WALL],
    [WALL, WALL, WALL, WALL, WALL, WALL, WALL,WALL],
)
 